### PR TITLE
datascript-todo ported to rum and figwheel

### PR DESCRIPTION
**Pull request by clifford**
Hi Nikita

I saw a recent request for you to port 'datascript-todo' to rum. I had done so back in January but never created the pull request. When I saw others interested in this I thought I may as well.

I does also has, figwheel, http-kit & bidi.

Will not be offended if you unhappy with the port.

Clifford

### CODE REVIEW

**Comment by hansgru** [comment]
+1 

Thank you very much for your port.

It would be nice if it would be included, since rum doesn't really have any usable examples right now :(.

**Comment by clifford** [comment]
Also checkout datascript-menu

**Comment by hansgru** [comment]
> Also checkout datascript-menu

@clifford 

Thanks :). I missed that one since I saw "Playground" and rum was not even mentioned :).

**Comment by tonsky** [comment]
@clifford sorry, but I want this to stay client-side only, just not to complicate matters. Thanks for PR though, but I just updated this project to Rum by myself

**Pull request closed without merging**
